# -*- coding: utf-8 -*-
"""Next word predictor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GDdmzWK5E4ATi3rhqatnuArk4yt9AhSn
"""

faqs="""PROGRAM OUTCOMES (POS)
PO1: Engineering Knowledge: Apply knowledge of mathematics, science,
engineering fundamentals and an engineering specialization to the solution complex
engineering problems.
PO2: Problem Analysis: Identify, formulate, research literature and analyze complex
engineering problems reaching substantiated conclusions using first principles of
mathematics, natural sciences and engineering sciences.
PO3: Design/ Development of Solutions: Design solutions for complex engineering
problems and design system components or processes that meet specified needs
with appropriate consideration for public health and safety, cultural, societal and
environmental considerations.
PO4: Conduct investigations of complex problems:Use research-based knowledge
and research methods including design of experiments, analysis and interpretation
of data and synthesis of information to provide valid conclusions.
PO5: Modern Tool Usage: Create, select and apply appropriate techniques,
resources and modern engineering and IT tools including prediction and modeling to
complex engineering activities with an understanding of the limitations.
PO6: The Engineer and Society:Apply reasoning informed by contextual knowledge
to assess societal, health, safety, legal and cultural issues and the consequent
responsibilities relevant to professional engineering practice.
PO7:  Environment and Sustainability: Understand the impact of professional
engineering solutions in societal and environmental contexts and demonstrate
knowledge of and need for sustainable development.
PO8: Ethics:Apply ethical principles and commit to professional ethics and
responsibilities and norms of engineering practice.
PO9: Individual and Team Work:Function effectively as an individual, and as a
member or leader in diverse teams and in multi-disciplinary settings.
PO10: Communication: Communicate effectively on complex engineering activities
with the engineering community and with society at large, such as being able to
comprehend and write effective reports and design documentation, make effective
presentations and give and receive clear instructions.
PO11: Project Management and Finance:Demonstrate knowledge and
understanding of engineering and management principles and apply these to one’s
own work, as a member and leader in a team, to manage projects and in
multidisciplinary environments.
PO12: Life-long Learning:Recognize the need for and have the preparation and
ability to Engage in independent and life- long learning in the broadest context of
technological Change.
PROGRAM SPECIFIC OUTCOMES (PSOs)
PSO1: To collect requirements, analyze, design, implement and test software
Systems.
PSO2:To analyze the errors and debug them within minimal time.
COURSE OVERVIEW:
Advanced Data Structures Laboratory course is to improve the programming skills using
CLanguage.This course covers implementing applications of linked lists and queues.
Thiscourse also enables to implement search trees and graphs , dictionaries and
hashing.Thecourse also enables to implementadvanced search tress and text processing.
After the completion of this course student will be able to implement efficient algorithm for
a software.

COURSE OUTCOMES (COs)

After the completion of the course, the student will be able to:
CO#  Course Outcomes
A8513.1  Implement programs using linear data structures to process data.
A8513.2 Implement operations on non-linear data structures for handling large data.
A8513.3 Build traversal algorithms for efficient search on nonlinear data structures.
A8513.4 Develop algorithms for text processing applications.
Circular Linked Lists: Circular Linked Lists are an extension of the traditional
linked list data structure. In this variant, the last node in the list points back
to the first node, forming a circular loop. This arrangement facilitates
seamless traversal from any point in the list to any other point, making it
particularly useful for scenarios where cyclic operations or continuous data
processing is required. Circular Linked Lists find applications in tasks such as
managing resources in a round-robin scheduling system or representing
cyclic structures in real-world scenarios.
Circular Queue using Linked List: A Circular Queue is a data structure that
follows the First-In-First-Out (FIFO) principle. When implemented with a
linked list, it allows for efficient management of a dynamic collection of
elements. The circular arrangement eliminates the need to shift elements
during enqueue and dequeue operations, providing a more optimized
solution. Circular Queues are employed in scenarios where a continuous
flow of data is desired, such as in network traffic buffering or job scheduling
in operating systems.
Deque using Linked List: Deque, short for double-ended queue, is a
versatile data structure that supports insertion and deletion at both ends.
When implemented with a linked list, it offers flexibility in managing data at
the front and rear ends efficiently. Deques find applications in situations
where dynamic and bidirectional data manipulation is essential, such as in
undo mechanisms in applications or managing a sliding window of data in
algorithms.
Addition of Two Polynomials: Polynomial addition involves combining like
terms from two polynomials by adding coefficients corresponding to the
same power of the variable. This operation is fundamental in algebraic
computations, including signal processing and cryptography. Implementing
polynomial addition efficiently is crucial for handling large datasets and
complex mathematical expressions.
Multiplication of Two Polynomials: Polynomial multiplication is the process
of multiplying each term of one polynomial by every term of the other. Thisoperation is pivotal in diverse fields, including computer graphics, error
correction codes, and numerical simulations. Efficient implementation of
polynomial multiplication using data structures like linked lists is essential
for optimizing computational resources and ensuring accurate results.
Heap Sort: Heap Sort is a comparison-based sorting algorithm that
leverages a binary heap data structure. By creating a heap and repeatedly
extracting the maximum element, Heap Sort achieves efficient sorting with
a consistent time complexity. This algorithm is widely used in scenarios
where a stable sorting solution is not critical, such as in embedded systems
or real-time applications.
Binary Search Trees: Binary Search Trees are hierarchical data structures
where each node has at most two children. The left child contains values
smaller than the node, while the right child contains values greater than the
node. Operations on Binary Search Trees include insertion, deletion,
searching, and traversal. These trees are employed in scenarios where
maintaining a sorted dataset and efficient search operations are paramount,
such as in database indexing or symbol tables in compilers.
Breadth First Search (BFS): Breadth First Search is a graph traversal
algorithm that explores all vertices at the current depth before moving on to
the next level. This algorithm is invaluable in applications such as social
network analysis, shortest path calculations, and network routing protocols.
BFS efficiently covers the breadth of a graph, making it suitable for scenarios
where a comprehensive exploration of the structure is required.
Depth First Search (DFS): Depth First Search is a graph traversal algorithm
that explores as far as possible along each branch before backtracking. DFS
is utilized in diverse applications, including maze solving, topological sorting,
and cycle detection in graphs. This algorithm provides insights into the
structure of a graph and is often chosen based on specific problem
requirements.

"""

import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
#tokenizer converts text -> numbers

tokenizer=Tokenizer()

print(type(faqs))

tokenizer.fit_on_texts([faqs])
#list of strings and sorts by frequncy

tokenizer.word_index

for sentence in faqs.split('\n'):
  print(sentence)

for senetence in faqs.split('\n'):
  print(tokenizer.texts_to_sequences([senetence])[0])

input_sequ=[]
for sentence in faqs.split('\n'):
  tokenized_sentence=tokenizer.texts_to_sequences([sentence])[0]
  print(tokenized_sentence)
  for i in range(1,len(tokenized_sentence)):
    input_sequ.append(tokenized_sentence[:i+1])

input_sequ

#input is of different size so make it same size by padding
max_len=max([len(x) for x in input_sequ])
max_len

from tensorflow.keras.preprocessing.sequence import pad_sequences
paded_input_sequences=pad_sequences(input_sequ,maxlen=max_len,padding='pre')
paded_input_sequences

X=paded_input_sequences[:,:-1]
y=paded_input_sequences[:,-1]

print(X.shape)
print(y.shape)

#it is a multi class classification so go for one-hot encoding
from tensorflow.keras.utils import to_categorical
y=to_categorical(y,num_classes=len(tokenizer.word_index)+1)

y.shape

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,LSTM,Dense
max_len = max([len(x) for x in input_sequ])
model=Sequential()
vocab_size = len(tokenizer.word_index) + 1
model.add(Embedding(vocab_size, 100, input_length=max_len-1))
# model.add(Embedding(283,100,input_length=max_len-1))
model.add(LSTM(150))
model.add(Dense(len(tokenizer.word_index)+1,activation='softmax'))
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])
model.build(input_shape=(None, max_len-1))
model.summary()

print(len(input_sequ))
print(max_len)

model.fit(X,y,epochs=100)

import time
import numpy as np
text = "program"

for i in range(10):
  # tokenize
  token_text = tokenizer.texts_to_sequences([text])[0]
  # padding
  padded_token_text = pad_sequences([token_text], maxlen=max([len(x) for x in input_sequ]), padding='pre')
  # predict
  pos = np.argmax(model.predict(padded_token_text))

  for word,index in tokenizer.word_index.items():
    if index == pos:
      text = text + " " + word
      print(text)
      time.sleep(2)